### ISSUE TITLE
Stack effect

### ISSUE THREAD

**Issue by egoist** [egoist/snackbar#16]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/egoist/snackbar/issues/16)

[Like this](https://zeit.co/design/toasts):

![stack](https://user-images.githubusercontent.com/8784712/59962888-02338880-951e-11e9-822f-0cf791b01040.gif)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#38 feat: add Stack effect](https://issuehunt.io/r/egoist/snackbar/pull/38)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/snackbar/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by kaiwoods** [comment]
is this intended to replace the existing positions, or build on top of them?
for example, could I have two notifications that display in the center, stacked, and one that displays on the right? or should all notifications now just stack in the bottom right / left?

**Comment by egoist** [comment]
> @plixcel: could I have two notifications that display in the center, stacked, and one that displays on the right?

Yes.
