### ISSUE TITLE
Documentation is not available

### ISSUE THREAD

**Issue by Romanchuk** [egoist/snackbar#33]
domain https://snackbar.egoist.sh/
ERR_SSL_PROTOCOL_ERROR

**Comment by egoist** [comment]
hmm it's working fine for me

Sergey Romanchuk <notifications@github.com> 于 2019年7月12日周五 上午11:42写道：

**Comment by Romanchuk** [comment]
I have this problem on both my computers.
Please make sure wevsites SSL Cert is correct

**Comment by egoist** [comment]
SSL is automatically managed by Netlify.com

<img width="846" alt="截屏2019-07-12下午8 06 51" src="https://user-images.githubusercontent.com/8784712/61127072-c5d1c780-a4e0-11e9-8862-375d61fb9233.png">

**Comment by Romanchuk** [comment]
I just opened it through VPN and it works.
And now it even works without VPN (because i guess i got cert now)

**Investigation**
Netlify.com - blocked for my provider (because of Russian law violation)
May be you should think about mirroring website
