### ISSUE TITLE
Support custom element in message?

### ISSUE THREAD

**Issue by hronro** [egoist/snackbar#49]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/egoist/snackbar/issues/49)

Is it possible to support adding custom elements (like icons) in message?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
### Submitted pull Requests
- [#51 feat: allow message to be a DOM node](https://issuehunt.io/r/egoist/snackbar/pull/51)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/snackbar/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by egoist** [comment]
Not possible for now, we can allow `message` to be a DOM node to fix this.

**Comment by egoist** [comment]
Thanks to @saltysugar, `message` can be a DOM node now.
